// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgXRDjfl22rvupsn-4w5qgc1u0Ekkjkw',
    appId: '1:551731316548:web:4d7956b65d3f5177cab911',
    messagingSenderId: '551731316548',
    projectId: 'gemini-app-clone',
    authDomain: 'gemini-app-clone.firebaseapp.com',
    storageBucket: 'gemini-app-clone.appspot.com',
    measurementId: 'G-SXCFVJLB9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejlKai7Ib7LNhmvIbn4BqY28ueUR28Is',
    appId: '1:551731316548:android:cb611b8510fa81b9cab911',
    messagingSenderId: '551731316548',
    projectId: 'gemini-app-clone',
    storageBucket: 'gemini-app-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvyKBK70OJCdZB5dFasBNCATLsJepQ_uM',
    appId: '1:551731316548:ios:9eb4beb34a2b98bdcab911',
    messagingSenderId: '551731316548',
    projectId: 'gemini-app-clone',
    storageBucket: 'gemini-app-clone.appspot.com',
    iosBundleId: 'com.example.geminiTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvyKBK70OJCdZB5dFasBNCATLsJepQ_uM',
    appId: '1:551731316548:ios:8ed4abb5dc5aa2bacab911',
    messagingSenderId: '551731316548',
    projectId: 'gemini-app-clone',
    storageBucket: 'gemini-app-clone.appspot.com',
    iosBundleId: 'com.example.geminiTutorial.RunnerTests',
  );
}
